name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1) Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # 2) Install dependencies via npm
      - name: Install dependencies
        run: npm ci

      # 3) Run your tests
      - name: Run tests
        run: npm test

      #- name: Run migrations
      #  run: npx prisma migrate deploy
      #  env:
      #    DATABASE_URL: ${{ secrets.DATABASE_URL }}
