name: CI

# Workflow to verify Shopify app build and deployment
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NODE_ENV: production
  DATABASE_URL: file:./prisma/dev.sqlite
  SHOPIFY_API_KEY: b71344c0cfcb41809d268ef9a06a431d
  SHOPIFY_APP_URL: https://carolina-concerns-kelly-continues.trycloudflare.com

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.10.0'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Setup Database
      run: npm run setup

    - name: Build
      run: npm run build
      env:
        SHOPIFY_API_KEY: ${{ env.SHOPIFY_API_KEY }}
        SHOPIFY_APP_URL: ${{ env.SHOPIFY_APP_URL }}
        SHOPIFY_API_SECRET: ${{ secrets.SHOPIFY_API_SECRET }} 